/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingInquiry = IDL.Record({
  'tripType' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
  'pickupCity' : IDL.Text,
  'pickupDate' : IDL.Text,
  'pickupTime' : IDL.Text,
  'mobile' : IDL.Text,
  'dropCity' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, BookingInquiry))],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingInquiry = IDL.Record({
    'tripType' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
    'pickupCity' : IDL.Text,
    'pickupDate' : IDL.Text,
    'pickupTime' : IDL.Text,
    'mobile' : IDL.Text,
    'dropCity' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, BookingInquiry))],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };